package com.playground.api.enums;

public enum ErrorCode {
    ITEM_ALREADY_EXISTS,
    UNSUPPORTED_OPERATION,
    INVALID_FILTER,
    ITEM_DOES_NOT_EXIST,
    INVALID_PARAMETERS,
    RUNTIME_ERROR,
    FILE_READ_ERROR,
    FILE_UPLOAD_ERROR,
    FILE_CONTENT_ERROR,
    INVALID_AUTHENTICATION,
}
