name: Build and Test the Application

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      # Database configuration
      DATABASE_HOST: "test"
      DATABASE_PORT: "test"
      DATABASE_NAME: "test"
      DATABASE_USER: "test"
      DATABASE_PASSWORD: "test"

      # Spring Security configuration
      SECURITY_USER_NAME: "test"
      SECURITY_USER_PASSWORD: "test"
      JWT_SECRET: "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest"
      JWT_ISSUER: "test"

      # AWS Configuration
      AWS_REGION: "test"
      AWS_S3_BUCKETS_DEFAULT: "test"
      AWS_ACCESS_KEY: "test"
      AWS_SECRET_KEY: "test"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Grant Execute Permissions to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
